garden = ('ромашка', 'роза', 'одуванчик', 'ромашка', 'гладиолус', 'подсолнух', 'роза', )
meadow = ('клевер', 'одуванчик', 'ромашка', 'клевер', 'мак', 'одуванчик', 'ромашка', )
garden_set = set(garden)
meadow_set = set(meadow)
print(garden_set.union(meadow_set))
print(garden_set.intersection(meadow_set))
print(garden_set.difference(meadow_set))
print(meadow_set.difference(garden_set))